### ISSUE TITLE
Refresh and best practice

### ISSUE THREAD

**Issue by cscetbon** [godaddy/kubernetes-external-secrets#263]
Reading the code I see there is a poller that checks for the version of the AWS secrets and updates them in k8s if they change. I also see that the polling can be disabled and that in that case Kubernetes events are watched regarding the secrets.

Am I right ? It should be noted that secrets are not updated automatically if used as environment variables for instance, and pods won't be restarted automatically. I think it should be noted somewhere

**Comment by Flydiverny** [comment]
Events for external secrets are always watched for, regardless of whether polling is enabled or disabled. Polling is enabled by default, and will trigger updates in the kubernetes secrets if anything happens to change in the secret backend.

I believe its to be expected that pods won't be magically restarted due to a secret object being reconfigured. This is left to how kubernetes behaves normally, one could for example probably use something like https://github.com/stakater/Reloader to

**Comment by cscetbon** [comment]
Thanks @Flydiverny, I'll definitely look at that other project. So you're saying that external secrets are always watched, and polling is more about updating the Kubernetes secrets right away or based on polling frequency ?
