### ISSUE TITLE
Is this project adopting the official Kubernetes client?

### ISSUE THREAD

**Issue by inductor** [godaddy/kubernetes-external-secrets#304]
[The godaddy/kubernetes client document](https://github.com/inductor/kubernetes-client/blob/master/merging-with-kubernetes.md) says it's merging with the Kubernetes client JavaScript.

Does that mean you have a plan to migrate it too?

**Comment by Flydiverny** [comment]
I honestly have no idea what the plan was there, but the PR to add fluent bindings to the official client has been stale for some months now https://github.com/kubernetes-client/javascript/pull/244

If that was finished I'm pretty sure KES would have migrated to it yes.

I think it might be worth migrating either way as it seems there are some issues starting to surface now due to using the https://github.com/godaddy/kubernetes-client client, which I'm not sure which versions it fully supports, it only mentions up to kubernetes 1.13 which is quickly becoming old.

**Comment by silasbw** [comment]
If https://github.com/godaddy/kubernetes-client is becoming an issue, yes we should migrate.

KES, however, doesn't depend on the statically generated bindings, instead of tries to generate client dynamically from the swagger/openapi spec (https://github.com/godaddy/kubernetes-external-secrets/blob/c4fdea666fc75eabdcdbf1a863902f295864b740/bin/daemon.js#L32).  So, the old static bindings shouldn't be a problem, but that doesn't mean godaddy/kubernetes-client isn't creating other (potentially related) issues.

**Comment by Flydiverny** [comment]
We've resolved the issues we had with kubernetes-client, so I don't see any reason for us to do this. But if someone magically makes a great PR swapping it out it would probably make sense to swap :) 

Anyway closing this for now!
