### ISSUE TITLE
aws secretmanager - dataFrom undefined

### ISSUE THREAD

**Issue by rosscdh** [godaddy/kubernetes-external-secrets#376]
Hi there, thanks for the great tool! Encountering a small issue with aws-sm and dataFrom

when creating a `dataFrom` secret on a confirmed and existing secret in SM

```
feature-AB-123-monkey-service-external   7s          ERROR, Cannot read property 'forEach' of undefined   27s
```

re-creating the secret with explicit json key->value references works

culprit appears to be here https://github.com/godaddy/kubernetes-external-secrets/blob/f26bf2bb14cfc7f6827e53550c8474b89133bc45/lib/poller.js#L226

secret works with direct key->value references so not auth problem

**Comment by Flydiverny** [comment]
Thought I wrote here, when I looked at this.. I'm really not sure how it can hit that code path if `externalDataFrom` is undefined. Considering the check just one line before.
If you are using a version before 3.2.0 though it will require `data`  to exist as well though. This was fixed in 3.2.0 by #292 when naming convention validation for `dataFrom` was added

@rosscdh please reopen if this is not the culprit :)
