### ISSUE TITLE
Question: is it possible to mount external secrets as volumes?

### ISSUE THREAD

**Issue by lhotrifork** [godaddy/kubernetes-external-secrets#58]
Hi,

Thanks for an awesome project. Is it possible to mount the external secrets as volumes in the pods? I could not find anything in the documentation.

Kind regards,
Lasse

**Comment by silasbw** [comment]
Hi @lhotrifork -- it's possible because External Secrets creates an actual `Secret` object that holds your sensitive data, so you can manipulate that `Secret` object (e.g., mount as volume in a `Pod`) the way you normally would.

You make a good point about the docs: they're lacking and we need to add some more explicit documentation around usage.  I'll leave this issue open to track the work to do that.

**Comment by lhotrifork** [comment]
That's great! 

Follow-up question: are secrets created from binary files supported?
For example secrets created like this:
`aws --profile $PROFILE --region $REGION secretsmanager create-secret  --name $NAME --secret-binary fileb://my-secret-file`

**Comment by JacopoDaeli** [comment]
Yes, they are supported. It does not matter how the secrets are created in secrets manager, as far as they are strings or valid `json` objects.

**Comment by JacopoDaeli** [comment]
@lhotrifork closing this in absence of follow up.

**Comment by gnaazr95** [comment]
Hi, just curious but to mount an external secret as a volume, should we be following this documentation: https://github.com/godaddy/kubernetes-external-secrets/blob/master/api.md?
